
export const PROFILE_UPDATED = "PROFILE_UPDATED";
export const PROFILE_CHANGE = "PROFILE_CHANGE";
export const PROFILE_FORM_RESET = "PROFILE_FORM_RESET";
export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS";