export const ADD_TRIP_CHANGE = "ADD_TRIP_CHANGE";

export const ADD_TRIP_SUCCESS = "ADD_TRIP_SUCCESS";
export const ADD_TRIP_FAILED = "ADD_TRIP_FAILED";
export const ADD_TRIP_PENDING = "ADD_TRIP_PENDING";
export const ADD_TRIP_IMG_PREVIEW = "ADD_TRIP_IMG_PREVIEW";


export const TRIP_UPDATED = "TRIP_UPDATED";

export const ADD_TRIP_FORM_RESET = "ADD_TRIP_FORM_RESET";

export const GET_TRIPS_SUCCESS = "GET_TRIPS_SUCCESS";

export const PROFILE_PICTURE_UPDATED = "PROFILE_PICTURE_UPDATED";

export const BACKGROUND_PICTURE_UPDATE_PENDING = "BACKGROUND_PICTURE_UPDATE_PENDING";

export const BACKGROUND_PICTURE_UPDATED = "BACKGROUND_PICTURE_UPDATED";