export const LOGIN_PENDING = "LOGIN_PENDING";
export const LOGIN_FULFILLED = "LOGIN_FULFILLED";
export const LOGIN_CHANGE = "LOGIN_CHANGE";
export const LOGIN_FORM_RESET = "LOGIN_FORM_RESET";
export const LOGIN_REJECTED = "LOGIN_REJECTED";